### PR TITLE
base-files: Adjust banner for Freifunk Vogtland

### PR DESCRIPTION
**Pull request by ecsv**
@SunboX Here are the adjustments (swimming pool cocktail and ascii art from pascal). I only noticed that the logo is too big for a normal 80 character terminal. The banner would now look like this

    ======================================================================================================
     _    __            __  __                __  ______          _ ____            __                __
    | |  / /___  ____ _/ /_/ /___ _____  ____/ / / ____/_______  (_) __/_  ______  / /__  ____  ___  / /_
    | | / / __ \/ __ `/ __/ / __ `/ __ \/ __  / / /_  / ___/ _ \/ / /_/ / / / __ \/ //_/ / __ \/ _ \/ __/
    | |/ / /_/ / /_/ / /_/ / /_/ / / / / /_/ _ / __/ / /  /  __/ / __/ /_/ / / / / ,< _ / / / /  __/ /_
    |___/\____/\__, /\__/_/\__,_/_/ /_/\__,_(_)_/   /_/   \___/_/_/  \__,_/_/ /_/_/|_(_)_/ /_/\___/\__/
              /____/
                    Reboot (17.01-SNAPSHOT, r3581+52-6b6578feec)
    ------------------------------------------------------------------------------------------------------
      Swimming Pool
    
      * 2cl Wodka
      * 6cl Ananassaft
      * 2cl Creme of Coconut
      * 1cl Blue Curacao
      * 2cl Sahne
      * 1 Stueck Stielkirsche
      * 1 Stueck Ananas
      * 20cl Crushed Ice
    ======================================================================================================

### CODE REVIEW

**Comment by SunboX** [comment]
Oh, schade. Da muss Pascal wohl noch mal ran ... ;)

Am 10. April 2018 um 21:42 schrieb Sven Eckelmann <notifications@github.com>:

@SunboX Here are the adjustments (swimming pool cocktail and ascii art from pascal). I only noticed that the logo is too big for a normal 80 character terminal. The banner would now look like this

======================================================================================================
 _    __            __  __                __  ______          _ ____            __                __
| |  / /___  ____ _/ /_/ /___ _____  ____/ / / ____/_______  (_) __/_  ______  / /__  ____  ___  / /_
| | / / __ \/ __ `/ __/ / __ `/ __ \/ __  / / /_  / ___/ _ \/ / /_/ / / / __ \/ //_/ / __ \/ _ \/ __/
| |/ / /_/ / /_/ / /_/ / /_/ / / / / /_/ _ / __/ / /  /  __/ / __/ /_/ / / / / ,< _ / / / /  __/ /_
|___/\____/\__, /\__/_/\__,_/_/ /_/\__,_(_)_/   /_/   \___/_/_/  \__,_/_/ /_/_/|_(_)_/ /_/\___/\__/
          /____/
                Reboot (17.01-SNAPSHOT, r3581+52-6b6578feec)
------------------------------------------------------------------------------------------------------
  Swimming Pool

  * 2cl Wodka
  * 6cl Ananassaft
  * 2cl Creme of Coconut
  * 1cl Blue Curacao
  * 2cl Sahne
  * 1 Stueck Stielkirsche
  * 1 Stueck Ananas
  * 20cl Crushed Ice
======================================================================================================
You can view, comment on, or merge this pull request online at:
  https://github.com/FreifunkVogtland/gluon/pull/4

Commit Summary
base-files: Adjust banner for Freifunk Vogtland
File Changes
A patches/lede/0052-base-files-Adjust-banner-for-Freifunk-Vogtland.patch (42)
Patch Links:
https://github.com/FreifunkVogtland/gluon/pull/4.patch
https://github.com/FreifunkVogtland/gluon/pull/4.diff

**Comment by ecsv** [comment]
What about a slightly shortened version (patch for that is now pushed)?

     ======================================================
      _    __            __  __                __
     | |  / /___  ____ _/ /_/ /___ _____  ____/ /
     | | / / __ \/ __ `/ __/ / __ `/ __ \/ __  /
     | |/ / /_/ / /_/ / /_/ / /_/ / / / / /_/ / 
     |___/\____/\__, /\__/_/\__,_/_/ /_/\__,_/.freifunk.net
               /____/
         Reboot (17.01-SNAPSHOT, r3581+52-6b6578feec)
     ------------------------------------------------------
      Swimming Pool
    
      * 2cl Wodka
      * 6cl Ananassaft
      * 2cl Creme of Coconut
      * 1cl Blue Curacao
      * 2cl Sahne
      * 1 Stueck Stielkirsche
      * 1 Stueck Ananas
      * 20cl Crushed Ice
     ======================================================

**Comment by SunboX** [comment]
looks good to me :)

**Comment by ecsv** [comment]
Pascal proposed a different version:

     ===========================================================
      _    __            __  __                __
     | |  / /___  ____ _/ /_/ /___ _____  ____/ /
     | | / / __ \/ __ `/ __/ / __ `/ __ \/ __  /
     | |/ / /_/ / /_/ / /_/ / /_/ / / / / /_/ / _
     |___/\____/\__, /\__/_/\__,_/_/ /_/\__,_/ (_)
               /____/
         ______          _ ____            __                __
        / ____/_______  (_) __/_  ______  / /__  ____  ___  / /_
       / /_  / ___/ _ \/ / /_/ / / / __ \/ //_/ / __ \/ _ \/ __/
      / __/ / /  /  __/ / __/ /_/ / / / / ,< _ / / / /  __/ /_
     /_/   /_/   \___/_/_/  \__,_/_/ /_/_/|_(_)_/ /_/\___/\__/
     Reboot (17.01-SNAPSHOT, r3581+52-6b6578feec)
     -----------------------------------------------------------
      Swimming Pool
    
      * 2cl Wodka
      * 6cl Ananassaft
      * 2cl Creme of Coconut
      * 1cl Blue Curacao
      * 2cl Sahne
      * 1 Stueck Stielkirsche
      * 1 Stueck Ananas
      * 20cl Crushed Ice
     ===========================================================

**Comment by SunboX** [comment]
Finde ich auch gut. Können wir gerne so einbauen.

**Pull request merged**
